### ISSUE TITLE
Fix time scraping on BBC Good food scraper

### ISSUE THREAD

**Issue by marcolussetti** [hhursev/recipe-scraper#14]
Doesn't appear to parse the time correctly.

Cfr. https://gist.github.com/marcolussetti/49c46c893cea474677a0d0e789817364 where I have some quick&dirty checking of some random live recipes.

**Comment by marcolussetti** [comment]
@hhursev I'll comment here but it pertains to all of them.

First of all, sorry for the spam of issues, just figured it best to file them individually.

I remembered playing around with the project a while back and remembered that I run into issues w/ BBC Food & Epicurious but figured that there might be more. I quickly put a script together that I've linked up there that just quickly gave me an idea if there's other things to tackle.

I'll try to tackle the issues I've filed either later tonight or in the next couple of days. I will leave My Baking Addiction & Fine Dining Lovers as last as the issues are different  from simple tweaking of the parsers it seems.

For the rest of them, please let me know if you prefer if I make atomic pull requests one for each parser or if you want me to bundle everything together into one. Whichever works easiest for you works for me :)

**Comment by hhursev** [comment]
Hey hey! Thanks for opening the issues - it’s good to know there are updates needed. If you manage to tackle some of them - that will be really great! I will take a look on the weekend too.

As for if I prefer one atomic PR or separate for every issue - I don’t really care. I’d probably do it in one as it seems easier. With #refs to the specific #issues fixed.

**Comment by marcolussetti** [comment]
Glad to be of some help :)
I've fixed all but the two https issues in PR #27 . I stuck to 1 commit per parser which references the specific issue.

I've noted some issues over at the PR that I run into so that you can see if my solution was ok.
