### ISSUE TITLE
Investigate why Fine Dining Lovers is returning 404s

### ISSUE THREAD

**Issue by marcolussetti** [hhursev/recipe-scraper#20]
The scraper is getting 404s whereas the links work fine on a real browser.

A simple `scrape_me('https://www.finedininglovers.com/recipes/brunch/rocket-gorgonzola-souffle/')` is sufficient to trigger the error.

I have done no investigation of what the issue might be, but I imagine it could just be returning 404s based on the user agent?

**Comment by marcolussetti** [comment]
Works just fine over HTTP.

**Comment by hhursev** [comment]
Hmm this is because `https://finedininglovers.com/recipes/brunch/rocket-gorgonzola-souffle/` return 404, and as of now we remove the `www.` part before I submit the request.

I’ll see what can be done in a few.
