### ISSUE TITLE
Investigate SSL certificate issue on My Baking Addiction

### ISSUE THREAD

**Issue by marcolussetti** [hhursev/recipe-scraper#21]
A simple `scrape_me('https://www.mybakingaddiction.com/tiramisu-trifles-recipe/')` is enough to trigger a certificate error. I quickly glanced at the error and it seemed like the certificate received was for test.mybakingaddiction.com which is weird as when opening the URL in a browser the correct certificate is used.

**Comment by marcolussetti** [comment]
Works just fine over HTTP.

**Comment by hhursev** [comment]
Absolutely the same as #20 which is good. We’ll get 2 rabbits with one hit :)
