### ISSUE TITLE
"Less than" times

### ISSUE THREAD

**Issue by za3k** [hhursev/recipe-scraper#8]
I've seen some times like: "Less than 30 minutes", "Under 1 hour", etc. Right now these get parsed as 0. Even if you want that, can you add some documentation to get_minutes explaining it?

**Comment by hhursev** [comment]
Hmm strange these should be getting parsed as 30 and 60 respectively. The TIME_REGEX should be catching those. Can you give me a link with such a recipe

**Comment by za3k** [comment]
Yeah, that should. My examples are from cookstr, which is broken without my PR (unmerged, https://github.com/hhursev/recipe-scraper/pull/6), so maybe I messed something up in that.
